// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUvMouEU9ESe2RoyHpcy4koK5g2kgWAxs',
    appId: '1:16319670280:web:2fac4fa9b5af7c608989bd',
    messagingSenderId: '16319670280',
    projectId: 'gtarp-organization',
    authDomain: 'gtarp-organization.firebaseapp.com',
    storageBucket: 'gtarp-organization.appspot.com',
    measurementId: 'G-WLERP8H71L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKWj1C66udpGS-jKajYqV4kCudETb563c',
    appId: '1:16319670280:android:8f6e000179b6cb2c8989bd',
    messagingSenderId: '16319670280',
    projectId: 'gtarp-organization',
    storageBucket: 'gtarp-organization.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAi9_R0B5OBaGiWy9OEK_UgRVdsj5tlk1I',
    appId: '1:16319670280:ios:ee50c3f6404ef7428989bd',
    messagingSenderId: '16319670280',
    projectId: 'gtarp-organization',
    storageBucket: 'gtarp-organization.appspot.com',
    iosBundleId: 'com.example.orgManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAi9_R0B5OBaGiWy9OEK_UgRVdsj5tlk1I',
    appId: '1:16319670280:ios:342d8c3f0ea5a8ca8989bd',
    messagingSenderId: '16319670280',
    projectId: 'gtarp-organization',
    storageBucket: 'gtarp-organization.appspot.com',
    iosBundleId: 'com.example.orgManagement.RunnerTests',
  );
}
